### PR TITLE
fix: delete indexedDB data on logout

### LINKED ISSUE #380: Log Out when Nextcloud logs out
Hi,

right now I am using both nextcloud and this app via OIDC (OpenID Connect), the iframe problem is still a problem, don't know why, put the frame-src into keycloak and nginx, but didn't work.

But the more problematic thing is, that synapse doesn't automatically logs sessions out, so when I log out with the nextcloud account and somebody else goes onto the computer and into the browser and logs into with their nextcloud account they are logged in into my messages.
Is it possible to send a logout message to synapse/matrix when nextcloud is logged out?

This feature request tries the complete opposite, so maybe this should be a toggle (on by default to log you out, as it is much more secure).
https://github.com/gary-kim/riotchat/issues/114

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #380 

@jonathanmmm could you check if this fixes your issue?

### CODE REVIEW

**Comment by jonathanmmm** [comment]
@gary-kim Should I try it by changing the specific files myself? The build didn't finish so 0.8.1 is not released.

**Comment by gary-kim** [comment]
The build system doesn't make a new version per PR. 

You can try installing it using the README installation instruction: https://github.com/gary-kim/riotchat/blob/master/README.md#installation

**Comment by jonathanmmm** [comment]
I tried changing the files manually but I can't find the .js files (probably compiled?).
Would be easy for you to just compile it and paste it here as a tar.gz or so?
Otherwise, I try it on another server to compile (want to keep my production server clean).

**Comment by jonathanmmm** [comment]
I did the following

```
git clone https://github.com/gary-kim/riotchat.git
cd riotchat
git checkout fix/380/delete-on-logout
git pull
git submodule update --init --recursive
make
```
und nach make kommt folgende Fehlermeldung:


```
(cd 3rdparty/riot-web && rm -rf ../riot && yarn && yarn add @nextcloud/browserslist-config && yarn build && cp config.sample.json webapp/ && cp element.io/develop/config.json webapp/develop.config.json && git describe --exact-match HEAD | cut -c 2- > webapp/version && mv webapp ../riot && yarn remove @nextcloud/browserslist-config) || (cd 3rdparty/riot-web && yarn remove @nextcloud/browserslist-config && exit 1)
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'remove'
make: *** [Makefile:17: 3rdparty/riot] Fehler 1
```
Fehler 1 means Error 1

Tried to access it anyways, but it just shows a blank page. 

I am using nextcloud-fpm docker container, so it is installed unter custom_apps. I stopped the container before installing it and starting the container after.

**Comment by jonathanmmm** [comment]
Same happens with the master branch, I installed yarn, npm, node-js, make.

**Comment by gary-kim** [comment]
Looks like you have the wrong Yarn:
https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one

**Comment by gary-kim** [comment]
Okay, I'll merge this for now.

**Pull request merged**
